import type { Metadata } from 'next'
import './globals.css'
import AppContainer from '@/components/app-container'

import { Inconsolata, Inter, Roboto, Staatliches } from 'next/font/google'

import '@fortawesome/fontawesome-svg-core/styles.css'
import { config } from '@fortawesome/fontawesome-svg-core'
import { LanguageProvider } from '@/context/LanguageContext'
import Navbar from '@/components/navbar/navbar'

config.autoAddCss = false

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
})

const staatliches = Staatliches({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-staat',
  weight: '400',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang='en' className={`${staatliches.variable} ${inter.variable}`}>
      <body>
        <AppContainer>
          <LanguageProvider>
            <Navbar />
            {children}
          </LanguageProvider>
        </AppContainer>
      </body>
    </html>
  )
}
